<header><!-- inicio cabeçalho -->
      <nav id="nav-fixa" class="navbar navbar-expand-sm navbar-light bg-warning fixed-top">
        <div class="container">
          <a href="#" class="navbar-brand">
            <!--<img src="img/logo.png" width="142">-->
          </a>
          <!-- Resposividade da barra principal-->
          <button class="navbar-toggler" data-toggle="collapse" 
          data-target="#nav-principal">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a href="#home" class="nav-link">Home</a>
              </li>
              <li class="nav-item">
                <a href="#recursos" class="nav-link">Recursos</a>
              </li>
              <li class="nav-item">
                <a href="#beneficios" class="nav-link">Benefícios</a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link">Preços</a>
              </li>
              <li class="nav-item">
                <a href="/entrar" class="btn btn-outline-light ml-4">Entrar</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header><!-- fim cabeçalho -->

    <section id="home"><!-- inicio seção home -->
      <div class="container">
        <div class="row">
          <div class="col-md-6 d-flex"><!-- inicio textos da seção -->  
            <div class="align-self-center">
              <h1 class="display-4">Suas consultas, descomplicadas</h1>
              <p>
                Usado por mais de 1 milhão de pessoas, o ConsulMed é uma ferramenta online que vai facilitar sua vida na hora de encontrar um médico.
              </p>
              <form class="mt-4 mb-4">
                <div class="input-group">
                  <!--<input type="text" placeholder="Seu e-mail" 
                  class="form-control">-->
                  <div class="input-group-append">
                    <a href="/inscreverse" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
                  </div>
                </div>
              </form>

              <p>Disponível para
                <a href="" class="btn btn-outline-light">
                  <i class="fab fa-android fa-lg"></i>
                </a>
                <!--<a href="" class="btn btn-outline-light">
                 	<i class="fab fa-apple fa-lg"></i>
                </a>-->
              </p>
            </div>
          </div><!-- fim textos da seção -->
      
          <div class="col-md-4 d-none d-md-block">
            <img src="img/medica.png" id="capa">
          </div>
        </div>
      </div>
    </section><!-- fim seção home -->

    <section class="caixa" id="recursos"><!--inicio da seção-->
      <div class="container">
        <div class="row">
          <div class="col-md-6 d-flex">
            <div class="align-self-center">
              <h2>Saiba todos seus atendimentos, tenha um historico personalizado em suas mãos</h2>
              <p>
                Com o ConsulMed, você categoriza todos os seus atendimentos. Com graficos simples, voce sabe a média de cada modalidade de atendimento da sua clinica.
              </p>
              <a href="" class="btn btn-primary">Veja mais</a>
            </div>
          </div>
          <div class="col-md-6">
            <img src="img/saiba.png" class="img-fluid">
          </div>
        </div>
      </div>
    </section><!--fim da seção-->

    <section class="caixa" id="beneficios"><!--inicio da seção juros-->
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <img src="img/juros.png" class="img-fluid">
          </div>
          <div class="col-md-6 d-flex">
            <div class="align-self-center">
              <h2>Espanda o alcace da sua clinica, mostre para todos que consultar com você é mais pratico e feliz</h2>
              <p>
                Telefonemas o dia todo é um problema? O ConsulMed avisa voce: receba alertas de consultas de novos pacientes em tempo real.
              </p>
              <a href="" class="btn btn-primary">Veja mais</a>
            </div>
          </div>
        </div>
      </div>
    </section><!--fim da seção juros-->

    <section class="caixa"><!--inicio da seção recursos-->
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <img src="img/facil.png" class="img-fluid">
            <h4>Fácil de usar</h4>
            <p>
              O ConsulMed vai além do básico e permite que você faça controles incríveis, essencias para a satisfação do seu cliente. Simples com tem que ser!
            </p>
          </div>
          <div class="col-md-4">
            <img src="img/economize.png" class="img-fluid">
            <h4>Economize seu tempo</h4>
            <p>
              Tempo é dinheiro! Em segundos, você tem tudo sob controle e aproveita seu tempo oferecendo um serviço de maior satisfação para seu cliente.
            </p>
          </div>
          <div class="col-md-4">
            <img src="img/suporte.png" class="img-fluid">
            <h4>Suporte amigo</h4>
            <p>
              Dúvidas? Perguntas? Nosso suporte super legal ajuda você! A gente ta aqui pra resolver seus problemas e deixar sua vida bem mais fácil!
            </p>
          </div>
        </div>
      </div>
    </section><!--fim da seção recusos-->

    <!--Rodapé-->
    <footer class="mt-4 mb-4">
      <div class="container">
        <div class="row">
          <div id="footer" class="col-md-8">
            <p>
              <a href="">Home</a>
              <a href="">Recursos</a>
              <a href="">Benefícios</a>
              <a href="">Preços</a>
            </p>
          </div>
          <div class="col-md-4 d-flex justify-content-end">
            <a href="" class="btn btn-outline-dark">
              <i class="fab fa-facebook fa-lg"></i>
            </a>
            <a href="" class="btn btn-outline-dark ml-2">
              <i class="fab fa-twitter fa-lg"></i>
            </a>
            <a href="" class="btn btn-outline-dark ml-2">
              <i class="fab fa-instagram fa-lg"></i>
            </a>
            <a href="" class="btn btn-outline-dark ml-2">
              <i class="fab fa-youtube fa-lg"></i>
            </a>
          </div>
        </div>
      </div>
    </footer>

  </div>
</div>