<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['nome_fantasia']?>" name="nome_fantasia" class="form-control" placeholder="Nome Fantasia">
              </div>
              
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['email']?>" name="email" class="form-control" placeholder="E-mail" onblur="verificaEmail(this.value)">
              </div>

              <div class="form-group">
                <input type="text" id="cnpj" class="form-control" name="cnpj" placeholder="CNPJ"
                onblur="verificaCNPJ(this.value)">
              </div>

              <div class="form-group">
                <input type="text" class="form-control" name="ocupacao" placeholder="Ex: Oftalmologista">
              </div>

              <div class="form-group">
                <input type="text" id="cep" class="form-control" name="cep" placeholder="CEP" onblur="buscacep(this.value)">
              </div>

              <div class="form-group">
                <input type="text" id="rua" class="form-control" name="rua" placeholder="Rua">
              </div>

              <div class="form-group">
                <input type="text" id="num_local" class="form-control" name="num_local" placeholder="Numero">
              </div>

              <div class="form-group">
                <input type="text" id="bairro" class="form-control" name="bairro" placeholder="Bairro">
              </div>

              <div class="form-group">
                <input type="text" id="cidade" class="form-control" name="cidade" placeholder="Cidade">
              </div>

              <div class="form-group">
                <input type="text" id="uf" class="form-control" name="uf" placeholder="UF">
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->usuario['senha']?>" name="senha" class="form-control" placeholder="Senha">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>

              <?php 

              if ($this->view->erroCadastro) { ?>
                <small class="form-text text-danger">*Erro ao tentar realizar cadastro, verifique se os campos foram preenchidos corretamente.</small>
              <?php } ?>

            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<script>
  function buscacep(cep){
    let url = 'https://viacep.com.br/ws/'+cep+'/json/unicode/'
    let xmlHttp = new XMLHttpRequest()
    xmlHttp.open('GET', url)

    xmlHttp.onreadystatechange = () => {
      if(xmlHttp.readyState == 4 && xmlHttp.status == 200){
        let dadosJson = xmlHttp.responseText
        let dadosJsonObj = JSON.parse(dadosJson)
        document.getElementById('rua').value = dadosJsonObj.logradouro
        document.getElementById('bairro').value = dadosJsonObj.bairro
        document.getElementById('cidade').value = dadosJsonObj.localidade
        document.getElementById('uf').value = dadosJsonObj.uf
        //console.log(dadosJsonObj)
      }
    }

    xmlHttp.send()
  }
</script>

<script type="text/javascript">
  var response;
  function verificaEmail(email){
    let dados = {email:email}
    $.ajax({
      type: 'post',
      url: 'http://192.168.15.142:8888/public/api/v1/usuarioclinica/lista/emailexistente',
      data: dados,
      dataType: 'json',
      success: dados => { response = dados; alertVerificacao()},
      error: erro => {alertErr()}
    });
  }

  function alertVerificacao(){
    if (response['status'] == 'email_existente') {
      alert('email em uso');
      window.location.reload();
    }
  }

  function alertErr(){
      alert('Erro inesperado a pagina será recarregada');
      window.location.reload();
  }

</script>

<script type="text/javascript">
  $(document).ready(function(){
    $('#cep').mask('00000-000');
    $('#cnpj').mask('00.000.000/0000-00');
  });
</script>

<script type="text/javascript">
  var response;
  function verificaCNPJ(cnpj){
    let dados = {cnpj:cnpj}
    $.ajax({
      type: 'post',
      url: 'http://192.168.15.142:8888/public/api/v1/usuarioclinica/lista/cnpjexistente',
      data: dados,
      dataType: 'json',
      success: dados => {response = dados; alertVerifiCNPJ()},
      error: erro => {alertErr()}
    });
  }

  function alertVerifiCNPJ(){
    if (response['status'] == 'cnpj_existente') {
      alert('CNPJ em uso');
      window.location.reload();
    }
  }

  function alertErr(){
      alert('Erro inesperado a pagina será recarregada');
      window.location.reload();
  }

</script>
