<?php

  //date_default_timezone_set('Brazil/East');
  $token = $_SESSION['token'];

  //$id = $this->view->info_usuario['id'];
  //session_start();
  $url = 'http://192.168.15.142:8888/public/api/v1/usuarioclinica/lista/consultasppendentes/'.$_SESSION['id'];
  $ch = curl_init($url);
  curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'X-Token:'.$token
  ));
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  $resposta = json_decode(curl_exec($ch));

  //foreach($resposta as $id_clinica => $value);
  
?>


<body id="page-top"><!--inicio body-->

  <!--nave para mascarar-->
  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
  </nav>
  <!--fim nave mascara-->

  <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">

    <a class="navbar-brand mr-1" href="#">ConsulMed</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
    <!-- Navbar Search -->
  </nav><!-- Navbar termina aqui -->

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/timeline">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Solicitações de consulta</span>
        </a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="#">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Consultas Pendentes</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/consultas_confirmadas">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Consultas Confirmadas</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="consultas_atendidas">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Consultas Atendidas</span>
        </a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>Indicadores</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Login Screens:</h6>
          <a class="dropdown-item">Login</a>
          <a class="dropdown-item">Register</a>
          <a class="dropdown-item">Forgot Password</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Other Pages:</h6>
          <a class="dropdown-item">404 Page</a>
          <a class="dropdown-item">Blank Page</a>
        </div>
      </li>
    </ul>
    <!--fim sidebar-->

    <div id="content-wrapper">

      <div class="container-fluid"><!--inicio conteudo-->
        <?php if ($resposta == null) { ?>
          <div class="container app">
            <div class="col-md-9">
              <div class="container pagina">
                <div class="row">
                  <div class="col">
                    <h4>Nenhuma de consulta pendende de confirmação :D</h4>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <?php }else{ ?>
                
        <?php foreach($resposta as $id_clinica => $value) {
          if ($value->status_consulta == null) {
         ?>
          <div class="container app">
            <div class="col-md-9">
              <div class="container pagina">
                <div class="row">
                  <div class="col">
                    <h4><?=$value->nomePaciente?></h4>
                    <hr/>
                    <div class="row mb-3 d-flex align-items-center tarefa">
                      <div class="col-sm-9">Tipo Consulta: <?=$value->tipoConsulta?></div>
                      <div class="col-sm-9">Data Marcada: <?=$value->DataConsulta?></div>
                      <div class="col-sm-9">Entre os dia(s): <?=$value->telefonePaciente?></div>
                    </div>
                    <hr/>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <?php } } } ?>
      </div><!--fim conteudo -->

      <!-- Sticky Footer -->
      <!--<footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Your Website 2019</span>
          </div>
        </div>
      </footer>-->

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

</body><!--fim body-->

<script type="text/javascript">
   $("#sidebarToggle").on('click', function(e) {
    e.preventDefault();
    $("body").toggleClass("sidebar-toggled");
    $(".sidebar").toggleClass("toggled");
  });
</script>

