	<header><!-- inicio cabeçalho -->
      <nav class="navbar navbar-expand-sm navbar-light bg-warning">
        <div class="container">
          <!-- Resposividade da barra principal-->
          <button class="navbar-toggler" data-toggle="collapse" 
          data-target="#nav-principal">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a href="/timeline">Solicitações de consultas</a>
              </li>
              <li class="nav-item">
	            <a href="/consultas_pendentes">Consultas pendentes</a>
	          </li>
              <li class="nav-item">
                <a href="/consultas_confirmadas">Consultas confirmadas</a>
              </li>
              <li class="nav-item">
                <a href="#">Consultas atendidas</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header><!-- fim cabeçalho -->

			<div class="container app">
				<div class="col-sm-9">
					<div class="container pagina">
						<div class="row">
							<div class="col">
								<h4>Todas as consultas do dia: 06/09/2019</h4>
								<hr />

								<div class="row mb-3 d-flex align-items-center tarefa">
									<div class="col-sm-9">Consulta 1</div>
									<div class="col-sm-3 mt-2 d-flex justify-content-between">
										<i class="fas fa-trash-alt fa-lg text-danger"></i>
										<i class="fas fa-edit fa-lg text-info"></i>
										<i class="fas fa-check-square fa-lg text-success"></i>
									</div>
								</div>

								<div class="row mb-3 d-flex align-items-center tarefa">
									<div class="col-sm-9">Consulta 2</div>
									<div class="col-sm-3 mt-2 d-flex justify-content-between">
										<i class="fas fa-trash-alt fa-lg text-danger"></i>
										<i class="fas fa-edit fa-lg text-info"></i>
										<i class="fas fa-check-square fa-lg text-success"></i>
									</div>
								</div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	
