<?php

	//date_default_timezone_set('Brazil/East');
	$token = $_SESSION['token'];

	//$id = $this->view->info_usuario['id'];
	//session_start();
	$url = 'http://192.168.15.142:8888/public/api/v1/usuarioclinica/lista/consultas/'.$_SESSION['id'];
	$ch = curl_init($url);
	curl_setopt($ch, CURLOPT_HTTPHEADER, array(
		'X-Token:'.$token
	));
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	$resposta = json_decode(curl_exec($ch));
	
?>


<!--<header> inicio cabeçalho 
  <nav class="navbar navbar-expand-sm navbar-light bg-warning fixed-top">
    <div class="container">
       Resposividade da barra principal
      <button class="navbar-toggler" data-toggle="collapse" 
      data-target="#nav-principal">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="nav-principal">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="#">Solicitações de consultas</a>
          </li>
          <li class="nav-item">
            <a href="/consultas_pendentes">Consultas pendentes</a>
          </li>
          <li class="nav-item">
            <a href="/consultas_confirmadas">Consultas confirmadas</a>
          </li>
          <li class="nav-item">
            <a href="/consultas_atendidas">Consultas atendidas</a>
          </li>
          <li class="nav-item">
            <a href="/sair">Sair</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header> fim cabeçalho -->

<body id="page-top"> <!--inicio bory-->

	<!--nave para mascarar-->
  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
  	<form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
  </nav>
  <!--fim nave mascara-->

  <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">

    <a class="navbar-brand mr-1" href="#">ConsulMed</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Pesquisr" aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
    <!-- Navbar Search -->
  </nav><!-- Navbar termina aqui -->

  <div id="wrapper">
    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Solicitações de consulta</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/consultas_pendentes">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Consultas Pendentes</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/consultas_confirmadas">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Consultas Confirmadas</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="consultas_atendidas">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Consultas Atendidas</span>
        </a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>Indicadores</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Login Screens:</h6>
          <a class="dropdown-item">Login</a>
          <a class="dropdown-item">Register</a>
          <a class="dropdown-item">Forgot Password</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Other Pages:</h6>
          <a class="dropdown-item">404 Page</a>
          <a class="dropdown-item">Blank Page</a>
        </div>
      </li>

      <li class="nav-item">
          <a href="/sair">Sair</a>
        </li>
    </ul>
    <!--fim sidebar-->

    <div id="content-wrapper">

      <div class="container-fluid"><!--inicio conteudo-->
        <?php if ($resposta == null) { ?>
			<div class="container app">
				<div class="col-md-9">
					<div class="container pagina">
						<div class="row">
							<div class="col">
								<h4>Nenhuma solicitação de consulta :D</h4>
							</div>
						</div>
					</div>
				</div>
			</div>
		<?php }else{ ?>
								
		<?php foreach($resposta as $id_clinica => $value) { 
				if ($value->status_consulta == null) {
				
			?>
			<div class="container app">
				<div class="col-md-9">
					<div class="container pagina">
						<div class="row">
							<div class="col">
								<h4><?=$value->nome_cliente?></h4>
								<hr/>
								<div class="row mb-3 d-flex align-items-center tarefa">
									<div class="col-sm-9">Tipo Consulta: <?=$value->tipo_consulta?></div>
									<div class="col-sm-9">Horario de preferencia: <?=$value->hora_preferencia?></div>
									<div class="col-sm-9">Entre os dia(s): <?=$value->data_preferencia?></div>
									<div class="col-sm-9">Aceita fora do periodo requisitado: 
										<?=$value->foraPeriodo?></div>
									<div class="col-sm-9">Telefone: <?=$value->telefone_cliente?></div>
								</div>
								<hr/>
								<!--Botão para acionar modal-->
								<button type="button" class="btn btn-success" id="btn-agendar"
								onclick="dados_paciente('<?=$value->id?>','<?=$value->nome_cliente?>',
								'<?=$_SESSION["id"]?>','<?=$value->id_cliente?>','<?=$_SESSION["nome_fantasia"]?>','<?=$value->tipo_consulta?>','<?=$value->telefone_cliente?>','<?=$value->nome_cliente?>','<?=$value->id?>')"
								data-toggle="modal" data-target="#ModalCentralizado">Agendar</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		<?php } } } ?>
      </div><!--fim conteudo -->

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Sticky Footer -->
	  <!--<footer class="sticky-footer">
	    <div class="container my-auto">
	      <div class="copyright text-center my-auto">
	        <span>Copyright © Your Website 2019</span>
	      </div>
	    </div>
	  </footer>-->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

</body><!--fim bory-->

<!-- Modal -->
<div class="modal fade" id="ModalCentralizado" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="nomePaciente"></h5>
      </div>
      <div class="modal-body">
      	<!--Conteudo-->
      	<div class="container">
			<div class="col-sm-10">
                <div class="input-group date" id="datetimepicker">
                	<h6>Data e hora da consulta</h6>
                	<input type="text" id="data_e_hora" placeholder=" Data e hora">
				    <span class="input-group-addon">
				    	<span class="glyphicon glyphicon-th"></span>
				    </span>
				</div>
			</div>
		</div>
		<!--fim-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" 
        data-dismiss="modal" onclick="limparCampo()">Fechar</button>
        <button type="button" class="btn btn-primary" id="btn-id" 
        onclick="pegarData()">Enviar Horario</button>
      </div>
    </div>
  </div>
</div>
<!--Fim modal-->


<!--JavaScrip que manda dados do usuario na url-->
<script type="text/javascript">
	var id_clinica;
	var id_consulta;
	var id_cliente;
	var nome_fantasia;
	var tipo_consulta;
	var telefone_cliente;
	var nome_cliente;
	var id_consulta;
	var resposta;
	//moment().format();
	function dados_paciente(id_consul, nome, id_clinic, id_client, nome_fanta, tipoConsul, foneCli, nomCli,id){
		document.getElementById("nomePaciente").innerHTML = "Sugerir horario para: "+nome;

		id_consulta = id_consul;
		id_cliente = id_client;
		id_clinica = id_clinic;
		nome_fantasia = nome_fanta;
		tipo_consulta = tipoConsul;
		telefone_cliente = foneCli;
		nome_cliente = nomCli;
		id_consulta = id;
	}

	function pegarData(){
	var temp = document.getElementById('data_e_hora').value;
	//console.log(temp);
	let dados = {
		id_clinica:id_clinica,
		id_paciente:id_cliente,
		nomeClinica:nome_fantasia,
		DataConsulta:temp,
		tipoConsulta:tipo_consulta,
		telefonePaciente:telefone_cliente,
		nomePaciente:nome_cliente
		
	}
	//console.log(dados); //dados => {console.log('error')}
	//let url = 'http://192.168.15.142:8888/public/api/v1/usuarioclinica/enviadata';
		$.ajax({
			type: 'post',
			url: 'http://192.168.15.142:8888/public/api/v1/usuarioclinica/enviadata',
			data: dados,
			dataType: 'json',
			success: function(){
				$.ajax({
					type: 'post',
					url: 'http://192.168.15.142:8888/public/api/v1/usuarioclinica/adiciona/status',
					data: {id:id_consulta,status_consulta:'pendente'},
					dataType: 'json',
					success: dados => {console.log('deu boa')},
					error: erro => {console.log('error')}
				});
				alert('Sucesso');
			},
			error: function(){
				alert('Erro tente novamente');
			}
			//error: dados = 'error'
		});
	}
//location.href = '/agendar_consulta?acao=agendar&id='+acao	
</script>

<!--Javascrip da hora-->
<script type="text/javascript">
	//var localTime = new Date();
	$('#datetimepicker').datetimepicker({
		fontAwesome: 'font-awesome',
		format: 'yyyy-mm-dd HH:ii',
		weekStart: 1,
		todayBtn: 1,
		autoclose: 1,
		todayHightlight: 1,
		startView: 2,
		forceParse: 0,
		showMeridian: 1,
		language: 'pt-BR',
		startDate: new Date(),
	});
</script>

<!--javascrip que limpa o campo text-->
<script type="text/javascript">
	function limparCampo() {
		$('#ModalCentralizado').on('click',function(){
			$(this).find('input:text').val('');
			window.location.reload();
		});
	}
</script>

<script type="text/javascript">
	 $("#sidebarToggle").on('click', function(e) {
    e.preventDefault();
    $("body").toggleClass("sidebar-toggled");
    $(".sidebar").toggleClass("toggled");
  });
</script>