<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Miniframework</title>

		<!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->

		<!--Bootstrap mim.css-->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<!--Bootstrap mim.js-->
		<!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>-->
		<!--Fontawesome-->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<!-- JS, Popper.js, e jQuery -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS 
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    -->
	    <script src="jquery-3.3.1.min.js"></script>
	    
	    <script type="text/javascript" src="sb-admin.js"></script>

		<!--Normalize-->
    	<!--<link rel="stylesheet" type="text/css" href="normalize/normalize.css">-->

		<link rel="stylesheet" type="text/css" href="/css/style.css"/>
		<link rel="stylesheet" type="text/css" href="/css/style-sidebar.css"/>


		<link rel="stylesheet" type="text/css" href="/datepicker/css/bootstrap-datepicker.css"/>
		<link rel="stylesheet" type="text/css" href="/datepicker/css/bootstrap-datetimepicker.min.css"/>
		<script src="/datepicker/js/bootstrap-datepicker.min.js"></script>
		<script src="/datepicker/js/bootstrap-datetimepicker.min.js"></script>
		<script src="/datepicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>
		<script src="/datepicker/locales/bootstrap-datetimepicker.pt-BR.js"></script>
		<script src="/datepicker/moment/moment.js"></script>
		<script src="/datepicker/moment/moment-locales.js"></script>
		<script src="/datepicker/moment/moment-locales-fuso.js"></script>
		<!--<script src="response.js"></script>-->

	</head>

	<body>
		<?= $this->content() ?>
	</body>

</html>